name: topicmodel
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - gensim
  - nltk
  - matplotlib
  - openjdk=8
  - pip:
    - coverage
    - pytest
    - pylint

